"use client";

import "./globals.css";
import { Poppins } from "next/font/google";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
